# Generated by Django 4.1 on 2023-12-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Academic_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="claim_email",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Academic_models.user",
            ),
            preserve_default=False,
        ),
    ]
