# Generated by Django 4.1 on 2023-12-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Academic_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
