# Generated by Django 4.1 on 2023-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Academic_models", "0002_alter_admin_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper_display",
            name="display",
        ),
        migrations.AddField(
            model_name="paper_display",
            name="author_id",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
