# Generated by Django 4.1 on 2023-12-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Academic_models", "0002_claim_claim_email_comment_comment_time_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="star_num",
        ),
    ]
