# Generated by Django 4.1 on 2023-12-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Academic_models",
            "0003_remove_paper_display_display_paper_display_author_id",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper_delete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_id", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Academic_models.comment",
            ),
        ),
    ]
