# Generated by Django 4.1 on 2023-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Academic_models", "0004_paper_delete_comment_reply_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_history",
            field=models.CharField(default="", max_length=100),
        ),
    ]
