# Generated by Django 4.1 on 2023-12-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Academic_models", "0005_user_chat_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
